[maxsize:4294967296]
[timeout:86400];

(
  relation
    (changed:"{{area_version}}","{{area_version}}")
    ["type"="multipolygon"]
    ["name"];
  relation
    (changed:"{{area_version}}","{{area_version}}")
    ["type"="boundary"]
    ["name"];
  relation
    (changed:"{{area_version}}","{{area_version}}")
    ["admin_level"]
    ["name"];
  relation
    (changed:"{{area_version}}","{{area_version}}")
    ["postal_code"];
  relation
    (changed:"{{area_version}}","{{area_version}}")
    ["addr:postcode"];
);

foreach->.pivot{
  (way(r.pivot);node(w););
  make_area[.pivot, no];
}

(
  way
    (changed:"{{area_version}}","{{area_version}}")
    ["area"="yes"]
    ["name"];
  way
    (changed:"{{area_version}}","{{area_version}}")
    ["building"]
    ["building"!="no"]
    ["name"]
    ["area"!="no"];
  way
    (changed:"{{area_version}}","{{area_version}}")
    ["highway"="services"]
    ["name"]
    ["area"!="no"];
  way
    (changed:"{{area_version}}","{{area_version}}")
    ["highway"="rest_area"]
    ["name"]
    ["area"!="no"];
  way
    (changed:"{{area_version}}","{{area_version}}")
    ["highway"="escape"]
    ["name"]
    ["area"!="no"];
  way
    (changed:"{{area_version}}","{{area_version}}")
    ["natural"]
    ["natural"!="no"]
    ["natural"!="coastline"]
    ["natural"!="ridge"]
    ["natural"!="arete"]
    ["natural"!="tree_row"]
    ["name"]
    ["area"!="no"];
  way
    (changed:"{{area_version}}","{{area_version}}")
    ["landuse"]
    ["landuse"!="no"]
    ["name"]
    ["area"!="no"];
  way
    (changed:"{{area_version}}","{{area_version}}")
    ["waterway"="riverbank"]
    ["name"]
    ["area"!="no"];
  way
    (changed:"{{area_version}}","{{area_version}}")
    ["waterway"="dock"]
    ["name"]
    ["area"!="no"];
  way
    (changed:"{{area_version}}","{{area_version}}")
    ["waterway"="boatyard"]
    ["name"]
    ["area"!="no"];
  way
    (changed:"{{area_version}}","{{area_version}}")
    ["waterway"="dam"]
    ["name"]
    ["area"!="no"];
  way
    (changed:"{{area_version}}","{{area_version}}")
    ["amenity"]
    ["amenity"!="no"]
    ["name"]
    ["area"!="no"];
  way
    (changed:"{{area_version}}","{{area_version}}")
    ["leisure"]
    ["leisure"!="no"]
    ["name"]
    ["area"!="no"];
  way
    (changed:"{{area_version}}","{{area_version}}")
    ["barrier"="city_wall"]
    ["name"]
    ["area"!="no"];
  way
    (changed:"{{area_version}}","{{area_version}}")
    ["barrier"="ditch"]
    ["name"]
    ["area"!="no"];
  way
    (changed:"{{area_version}}","{{area_version}}")
    ["barrier"="hedge"]
    ["name"]
    ["area"!="no"];
  way
    (changed:"{{area_version}}","{{area_version}}")
    ["barrier"="retaining_wall"]
    ["name"]
    ["area"!="no"];
  way
    (changed:"{{area_version}}","{{area_version}}")
    ["barrier"="wall"]
    ["name"]
    ["area"!="no"];
  way
    (changed:"{{area_version}}","{{area_version}}")
    ["barrier"="spikes"]
    ["name"]
    ["area"!="no"];
  way
    (changed:"{{area_version}}","{{area_version}}")
    ["railway"="station"]
    ["name"]
    ["area"!="no"];
  way
    (changed:"{{area_version}}","{{area_version}}")
    ["railway"="turntable"]
    ["name"]
    ["area"!="no"];
  way
    (changed:"{{area_version}}","{{area_version}}")
    ["railway"="roundhouse"]
    ["name"]
    ["area"!="no"];
  way
    (changed:"{{area_version}}","{{area_version}}")
    ["railway"="platform"]
    ["name"]
    ["area"!="no"];
  way
    (changed:"{{area_version}}","{{area_version}}")
    ["boundary"]
    ["boundary"!="no"]
    ["name"]
    ["area"!="no"];
  way
    (changed:"{{area_version}}","{{area_version}}")
    ["man_made"]
    ["man_made"!="no"]
    ["man_made"!="cutline"]
    ["man_made"!="embankment"]
    ["man_made"!="pipeline"]
    ["name"]
    ["area"!="no"];
  way
    (changed:"{{area_version}}","{{area_version}}")
    ["power"="generator"]
    ["name"]
    ["area"!="no"];
  way
    (changed:"{{area_version}}","{{area_version}}")
    ["power"="station"]
    ["name"]
    ["area"!="no"];
  way
    (changed:"{{area_version}}","{{area_version}}")
    ["power"="sub_station"]
    ["name"]
    ["area"!="no"];
  way
    (changed:"{{area_version}}","{{area_version}}")
    ["power"="transformer"]
    ["name"]
    ["area"!="no"];
  way
    (changed:"{{area_version}}","{{area_version}}")
    ["place"]
    ["place"!="no"]
    ["name"]
    ["area"!="no"];
  way
    (changed:"{{area_version}}","{{area_version}}")
    ["shop"]
    ["shop"!="no"]
    ["name"]
    ["area"!="no"];
  way
    (changed:"{{area_version}}","{{area_version}}")
    ["aeroway"]
    ["aeroway"!="no"]
    ["aeroway"!="taxiway"]
    ["name"]
    ["area"!="no"];
  way
    (changed:"{{area_version}}","{{area_version}}")
    ["tourism"]
    ["tourism"!="no"]
    ["name"]
    ["area"!="no"];
  way
    (changed:"{{area_version}}","{{area_version}}")
    ["historic"]
    ["historic"!="no"]
    ["name"]
    ["area"!="no"];
  way
    (changed:"{{area_version}}","{{area_version}}")
    ["public_transport"]
    ["public_transport"!="no"]
    ["name"]
    ["area"!="no"];
  way
    (changed:"{{area_version}}","{{area_version}}")
    ["office"]
    ["office"!="no"]
    ["name"]
    ["area"!="no"];
  way
    (changed:"{{area_version}}","{{area_version}}")
    ["building:part"]
    ["building:part"!="no"]
    ["name"]
    ["area"!="no"];
  way
    (changed:"{{area_version}}","{{area_version}}")
    ["military"]
    ["military"!="no"]
    ["name"]
    ["area"!="no"];
  way
    (changed:"{{area_version}}","{{area_version}}")
    ["craft"]
    ["craft"!="no"]
    ["name"]
    ["area"!="no"];
);

foreach->.pivot{
  (.pivot->.pivot;node(w.pivot););
  make_area[.pivot, no];
}
