sudo: required
dist: trusty

language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get update -qq || true
  - sudo apt-get install -y expat libexpat1-dev liblz4-dev libfcgi-dev zlib1g-dev libbz2-dev libicu-dev
  
before_script:  
  - mkdir -p $HOME/overpass
  - pushd src/
  - chmod u+x test-bin/*.sh
  - autoscan
  - aclocal
  - autoheader
  - libtoolize
  - automake --add-missing
  - autoconf
  - popd
  - mkdir -p build
  - cd build
  - ../src/configure CXXFLAGS="-std=c++11 -O2 -I/home/travis/build/mmd-osm/Overpass-API/src/third_party/libosmium/include -I/home/travis/build/mmd-osm/Overpass-API/src/third_party/protozero/include -I/home/travis/build/mmd-osm/Overpass-API/src/third_party/xxhash" LDFLAGS="-lpthread -lbz2 -licuuc -licui18n" --prefix=$EXEC_DIR --enable-lz4 --enable-fastcgi --enable-tests

script:  
  - make V=0 install -j3
  - cp -R test-bin/ bin/ cgi-bin/ ../src
  - export PATH=$PATH:$HOME/overpass/bin:$HOME/overpass/cgi-bin:$HOME/overpass/test-bin  
  - cd ../osm-3s_testing
  - ../src/test-bin/run_testsuite.sh 200

branches:
  only:
    - test758_lz4hash
    - test759

os:
  - linux
  
env:
  - EXEC_DIR=$HOME/overpass


