language: cpp

compiler:
  - gcc

before_install:
  - sudo add-apt-repository ppa:gezakovacs/lz4 -y
  - sudo apt-get update  -q 
  - sudo apt-get install -y expat libexpat1-dev 
#  - sudo pip install cpp-coveralls
# Travis uses some older Ubuntu version...
  - sudo apt-get install -y liblz4-dev
  - sudo pip install cpp-coveralls
  
before_script:  
  - mkdir -p $HOME/overpass
  - pushd src/
  - chmod u+x test-bin/*.sh
  - autoscan
  - aclocal
  - autoheader
  - libtoolize
  - automake --add-missing
  - autoconf
  - popd
  - mkdir -p build
  - cd build
#  - ../src/configure CXXFLAGS="-O3" --prefix=$EXEC_DIR
  - ../src/configure CXXFLAGS="-ggdb -fprofile-arcs -ftest-coverage" LDFLAGS="-lgcov" --prefix=$EXEC_DIR

script:  
  - make -j3
  - cp -R test-bin/ bin/ cgi-bin/ ../src
  - export PATH=$PATH:$HOME/overpass/bin:$HOME/overpass/cgi-bin:$HOME/overpass/test-bin  
  - cd ../osm-3s_testing
  - ../src/test-bin/run_testsuite.sh 200

after_success:
#  - cd ../build
#  - ln -s ../src/ .
#  - ln -s ../src/ overpass_api/src
  - coveralls -b build --exclude lib --exclude tests --gcov-options '\-lp'

branches:
  only:
    - test754

os:
  - linux
  
env:
  - EXEC_DIR=$HOME/overpass

