sudo: required
dist: focal

language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get update -qq || true
  - sudo apt-get install -y expat libexpat1-dev liblz4-dev libfcgi-dev zlib1g-dev libbz2-dev libicu-dev libfmt-dev libpcre2-dev libcereal-dev
  
before_script:  
  - mkdir -p $HOME/overpass
  - pushd src/
  - chmod u+x test-bin/*.sh
  - autoscan
  - aclocal
  - autoheader
  - libtoolize
  - automake --add-missing
  - autoconf
  - popd
  - mkdir -p build
  - cd build
  - ../src/configure CXXFLAGS="-Werror=implicit-function-declaration  -D_FORTIFY_SOURCE=2 -fexceptions -fpie -Wl,-pie -fpic -shared -fstack-protector-strong -Wl,--no-as-needed -pipe -Wl,-z,defs -Wl,-z,now -Wl,-z,relro -fno-omit-frame-pointer -flto -fwhole-program  -O2" LDFLAGS="-flto -fwhole-program -lfmt" --prefix=$EXEC_DIR --enable-lz4 --enable-fastcgi --enable-tests

script:  
  - make V=0 install -j3
  - cp -R test-bin/ bin/ cgi-bin/ ../src
  - export PATH=$PATH:$HOME/overpass/bin:$HOME/overpass/cgi-bin:$HOME/overpass/test-bin  
  - cd ../osm-3s_testing
  - ../src/test-bin/run_testsuite.sh 200

branches:
  only:
    - test758_lz4hash
    - test759

os:
  - linux
  
env:
  - EXEC_DIR=$HOME/overpass


