name: Docker Image CI

on:
  push:
    branches: [ test7591 ]
  pull_request:
    branches: [ test7591 ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file docker/Dockerfile_cmake --tag overpass:$(date +%s)
